#!/bin/bash

# pre-commit hook to run the ruff linter for backend
LINTER_OUTPUT=$(ruff check > /dev/null 2>&1)
LINTER_EXIT_CODE=$?

if [ $LINTER_EXIT_CODE -ne 0 ]; then
	echo -e "ERROR: The linter found issues. Please fix the issues before committing."
    echo -e "If this is intended, you can bypass the hook with 'git commit --no-verify'."
    echo -e $LINTER_OUTPUT
	exit 1
fi

# pre-commit hook to check formatting
FORMATTER_OUTPUT=$(ruff format --check > /dev/null 2>&1)
FORMATTER_EXIT_CODE=$?

if [ $FORMATTER_EXIT_CODE -ne 0 ]; then
	echo -e "ERROR: The formatter found issues. Please fix the issues before committing."
    echo -e "If this is intended, you can bypass the hook with 'git commit --no-verify'."
    echo -e $FORMATTER_OUTPUT
	exit 1
fi

# pre-commit hook to run unit tests
UNITTEST_OUTPUT=$(.venv/bin/python -m unittest > /dev/null 2>&1)
UNITTEST_EXIT_CODE=$?

if [ $UNITTEST_EXIT_CODE -ne 0 ]; then
	echo -e "ERROR: At least one backend unit test failed. Please fix the issues before committing."
    echo -e "If this is intended, you can bypass the hook with 'git commit --no-verify'."
    echo -e $UNITTEST_OUTPUT
	exit 1
fi

exit 0 # Allow the commit to proceed
