[project]
name = "shovl"
version = "0.3.0"
description = "A lightweight terminal-based database and S3 client built with Textual."
readme = "README.md"
authors = [
    { name = "Max Brixner" }
]
requires-python = ">=3.12.9"
dependencies = [
    "boto3>=1.43.96",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.54",
    "textual>=8.2.8",
    "typer>=0.27.2",
]
license = { file = "LICENSE.md" }
keywords = ["database", "AWS", "S3", "terminal", "TUI", "textual", "sqlalchemy", "boto3"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent"
]

[project.urls]
Source = "https://github.com/maxbrixner/shovl"
Issues = "https://github.com/maxbrixner/shovl/issues"

[project.scripts]
shovl = "shovl:main"

[project.optional-dependencies]
postgresql = [
    "psycopg2-binary>=2.9.13",
]
oracle = [
    "oracledb>=26.0.0",
]
mysql = [
    "pymysql>=1.2.2",
]
snowflake = [
    "snowflake-sqlalchemy>=1.11.1",
]
duckdb = [
    "duckdb>=1.5.5",
]
ibmdb = [
    "ibm-db-sa>=0.4.4",
]
dev = [
    "basedpyright>=1.40.1",
    "debugpy>=1.8.22",
    "ruff>=0.16.8",
]

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 80
target-version = "py314"

[tool.ruff.lint]
extend-select = ["ANN"]
ignore = ["ANN401"]

[tool.basedpyright]
typeCheckingMode = "strict"
